version: '3'
services:
  postgres_db:
    image: postgres:10.4-alpine
    restart: always
  banking:
    build: .
    command: bash -c "mix ecto.create && mix ecto.migrate && mix phx.server"
    ports:
      - "4000:4000"
    depends_on:
      - postgres_db
